GET http://localhost:8080/all
Accept: application/json
###
GET http://localhost:8080/richest
###
GET http://localhost:8080/find/Bill
###
POST http://localhost:8080 HTTP/1.1
content-type: application/json

{
    "name": "Jeff",
    "surname": "Bezos",
    "fortune": 113
}
